### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by bpbond** [krlmlr/mockr#1]
Perhaps note that `mockr` doesn't seem to be (in my testing) _exactly_ a drop-in replacement. In particular, there are cases where `testthat::with_mock` required a namespace qualifier, and things won't work if you use that in `mockr`. E.g. when calling an un-exported function:

```R
# testthat version
test_that("run_chunk runs chunk", {
  with_mock(
    module_sample_sample = function(...) TRUE,
    expect_true(gcamdata:::run_chunk("module_sample_sample", 1))
  )
})
```

needs to be written as 

```R
# mockr version
test_that("run_chunk runs chunk", {
  with_mock(
    module_sample_sample = function(...) TRUE,
    expect_true(run_chunk("module_sample_sample", 1))
  )
})
```

to run successfully now. Anyway, FYI. Thanks.

**Comment by krlmlr** [comment]
Thanks for bringing this up. I've been able to replicate the problem by changing the relevant parts of your package.

While there may be ways to make this work, I doubt it's worth the effort, because you really shouldn't need to use `<your-package>::` or `<your-package>:::` in your package or test code.
